export const videos = [
  {
    id: "1",
    title: "Music Box : Reflection",
    thumbnail: "/ic1.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/IElUjUUHkq4?si=gp5h07squ8mZAxpo",
  },
  {
    id: "2",
    title: "What If...",
    thumbnail: "/ic2.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/QHLVk1JI8XI?si=iwcdcpscMvv4Y3cW",
  },
  {
    id: "3",
    title: "Pandora's Box",
    thumbnail: "/ic3.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/pEOcNV-b_tM?si=MKqa-xpahyTAak3B",
  },
  {
    id: "4",
    title: "Arson",
    thumbnail: "/ic4.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/QmpTkkaKYSU?si=LvLMSWHp39okYMe8",
  },
  {
    id: "5",
    title: "STOP",
    thumbnail: "/ic5.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/KA08p22Jk_c?si=54oiHPnps4CtXppp",
  },
  {
    id: "6",
    title: "MORE",
    thumbnail: "/ic6.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/pKdBFeewZYE?si=zgKsDlkasLEsosMM",
  },
  {
    id: "7",
    title: "on the street",
    thumbnail: "/ic7.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/r6WbbU_lLCA?si=zQmNTTgvj109MkNM",
  },
  {
    id: "8",
    title: "lock / unlock",
    thumbnail: "/ic8.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/tOaWhRATZqk?si=v6ouM8CsDkbfuwWN",
  },
  {
    id: "9",
    title: "i don't know",
    thumbnail: "/ic9.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/MWVGgSE9MZg?si=uiEAbjqeQkU7qper",
  },
  {
    id: "10",
    title: "i wonder...",
    thumbnail: "/ic10.png?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/SeZouxOauPw?si=ydQhhCCL1FV_YcSB",
  },
  {
    id: "11",
    title: "Trivia 起 : Just Dance",
    thumbnail: "/ic11.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/_xjZtbeKd4E?si=VV2yvbNP-98StG6S",
  },
  {
    id: "12",
    title: "Sweet Dreams",
    thumbnail: "/ic12.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/kW1e8NtdW90?si=5D7hWnm8otQLi1kw",
  },
  {
    id: "13",
    title: "Mona Lisa",
    thumbnail: "/ic13.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/ECqGCH1TfLY?si=HpJBroN8UQDLXy8S",
  },
  {
    id: "14",
    title: "Base Line",
    thumbnail: "/ic14.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/e8loM2YykmE?si=Ci63xJHFTn2uNCnu",
  },
  {
    id: "15",
    title: "항상",
    thumbnail: "/ic15.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/Uy65Fo4H294?si=xx2Z5sQUlAqhxW7x",
  },
  {
    id: "16",
    title: "Airplane",
    thumbnail: "/ic16.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/8O_MwlZ2dEg?si=4bljzMaUQr5O2lQI",
  },
  {
    id: "17",
    title: "Airplane pt. 2",
    thumbnail: "/ic17.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/4DCOsbO27oY?si=vMAS99Auz-HuPZEa",
  },
  {
    id: "18",
    title: "Mic Drop",
    thumbnail: "/ic18.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/Fbhb49fZ5Lw?si=mOYoQ0tQIGAaH98e",
  },
  {
    id: "19",
    title: "SilverSpoon",
    thumbnail: "/ic19.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/T4vc-f-uQYA?si=NNH4Ts2VTw_zqdiI",
  },
  {
    id: "20",
    title: "Daydream",
    thumbnail: "/ic20.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/OK3GJ0WIQ8s?si=RyAoOsgxcjBVG2Rm",
  },
  {
    id: "21",
    title: "Chicken Noodle Soup",
    thumbnail: "/ic21.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/i23NEQEFpgQ?si=IMM0v8WXM1T54XW9",
  },
  {
    id: "22",
    title: "Hope World",
    thumbnail: "/ic22.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/M1mKyHWTrdc?si=adMeJHoSXXXGwiOf",
  },
  {
    id: "23",
    title: "= (Equal Sign)",
    thumbnail: "/ic23.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/_hNuNiNhcI4?si=sg7m6leOGtaj24dC",
  },
  {
    id: "24",
    title: "Future",
    thumbnail: "/ic24.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/Fh2PTrTaxv0?si=kxanpuq1-1sIFkn6",
  },
  {
    id: "25",
    title: "NEURON",
    thumbnail: "/ic25.jpg?height=720&width=1280",
    videoUrl: "https://www.youtube.com/embed/z4Rg_VgOlJU?si=qRH1a39wQpp0I9KF",
  },
]
